### ISSUE TITLE
Number of classes used by sturgeon

### ISSUE THREAD

**Issue by rowanhowellGE** [marcpaga/sturgeon#6] opened 2023-12-07 16:57 UTC
Hi,

The GitHub page says that there are  91 classes (9 control and 82 tumor classes), which matches the original Capper et al. (2018) paper. However, when I run sturgeon I get 87 classes. It looks like some have been combined eg "Ependymal - SUBEPN - ALL", rather than SUBEPN PF, ST and SPINE categories. Is this intended behaviour? 

I am using version 3.6.3 but looking at release notes, it doesn't look like anything that would effect this has changed in more recent versions.

Thanks,
Rowan

**Comment by marcpaga** [comment] 2023-12-08 09:19
Hi Rowan,

This is a mistake on the README file, there are indeed some merged classes. This is the intended behaviour, and this behaviour hasn't been changed while this repo has been public. I will update the README with the relevant info. But here are the merged classes:

`Embryonal - MB SHH - CHL AD INF` merges: `"Embryonal - MB SHH - CHL AD", "Embryonal - MB SHH - INF"`
`Ependymal - SUBEPN - ALL` merges: `"Ependymal - SUBEPN - PF", "Ependymal - SUBEPN - SPINE", "Ependymal - SUBEPN - ST"`
`Other glioma - LGG PA - PA` merges: `"Other glioma - LGG PA - PA MID", "Other glioma - LGG PA - PA PF"`

This was done because the subtypes for these classes were either based on tumour location or age. 

If you'd want to play with the merging of classes, inside the model.zip file there's a json file called `merge.json` where the merging of certain classes is defined.

**Closed as completed** 2023-12-08 09:40 UTC
Labels: documentation
